In [2]:
import pandas as pd
import numpy as nm

In [3]:
names= ['Class', 'Alcohol', 'Malic acid', 'Ash', 'Alcalinity of ash', 'Magnesium', 'Total phenols', 'Flavanoids',
    'Nonflavanoid phenols', 'Proanthocyanins', 'Color intensity', 'Hue', 'OD280/OD315 of diluted wines', 'Proline']
names_of_class = ['Class']
names_of_features = names[1:]
data = pd.read_csv('wine.data', header=None, names = names, index_col = False)

In [17]:
# разделим признаки и классы
fdata = data.drop('Class',axis=1) #данные фич
cdata = data.Class #данные классов
#используем масштабирование признаков
from sklearn.preprocessing import scale 
fdata = scale(fdata)

In [18]:
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

In [19]:
kf = KFold(n_splits=5, random_state=42, shuffle=True)

In [20]:
from sklearn.neighbors import KNeighborsClassifier
knn = []
scores = []
from sklearn.model_selection import cross_val_score

In [21]:
# первый вариант - используем cross_val_score.
# она сама создаст разбиения по переданному KFold, обучит модели и проверит на тестовых выборках
for k in range(1,51):
    knn.append(KNeighborsClassifier(n_neighbors=k))
    scores.append(cross_val_score(knn[k-1], fdata, cdata.values, cv = kf))

In [22]:
#средние scores в первом варианте
meanscores = []
for i in range(1,51):
    meanscores.append(scores[i-1].mean())
    print("K=" + str(i) + ": " + str(scores[i-1].mean()))

K=1: 0.943968253968254
K=2: 0.9328571428571429
K=3: 0.9550793650793651
K=4: 0.9382539682539683
K=5: 0.9493650793650794
K=6: 0.9495238095238095
K=7: 0.9495238095238095
K=8: 0.9552380952380952
K=9: 0.9607936507936508
K=10: 0.9607936507936508
K=11: 0.9609523809523809
K=12: 0.9552380952380952
K=13: 0.9495238095238093
K=14: 0.9663492063492063
K=15: 0.9720634920634922
K=16: 0.9720634920634922
K=17: 0.9665079365079364
K=18: 0.9665079365079364
K=19: 0.9553968253968254
K=20: 0.9665079365079364
K=21: 0.9609523809523811
K=22: 0.9665079365079364
K=23: 0.9609523809523809
K=24: 0.9552380952380952
K=25: 0.9552380952380952
K=26: 0.9607936507936508
K=27: 0.9552380952380952
K=28: 0.9663492063492063
K=29: 0.9776190476190475
K=30: 0.9607936507936508
K=31: 0.9552380952380952
K=32: 0.9607936507936508
K=33: 0.9663492063492063
K=34: 0.9663492063492063
K=35: 0.9607936507936508
K=36: 0.9607936507936508
K=37: 0.9552380952380952
K=38: 0.9607936507936508
K=39: 0.9607936507936508
K=40: 0.9607936507936508
K=41: 0.9663492063492063
K=42: 0.9607936507936508
K=43: 0.9663492063492063
K=44: 0.9606349206349206
K=45: 0.9663492063492063
K=46: 0.9495238095238095
K=47: 0.9550793650793651
K=48: 0.9495238095238095
K=49: 0.9550793650793651
K=50: 0.9606349206349206

In [24]:
#второй вариант. Делаем цикл по K, а в нем - по разбивкам
#сами обучаем и вычисляем score
knn2 = []
k_accuracy = []
for k in range(1,51):
    knn2.append(KNeighborsClassifier(n_neighbors=k))
    accuracy = []
    for train_index, test_index in kf.split(fdata):
        #print("TRAIN:", train_index, "TEST:", test_index)
        X_train, X_test = fdata[train_index], fdata[test_index]
        y_train, y_test = cdata.loc[train_index], cdata.loc[test_index]
        knn2[k-1].fit(X_train, y_train.values.ravel())
        thescores = knn2[k-1].score(X_test, y_test.values.ravel())
        #print(thescores)
        accuracy.append(thescores)
    k_accuracy.append(nm.mean(accuracy))    
#print (k_accuracy)

In [25]:
accdata = pd.DataFrame(meanscores, columns=['Meth.1'])

In [26]:
accdata['Meth.2'] = pd.DataFrame(k_accuracy)

In [28]:
accdata.max()

Meth.1    0.977619
Meth.2    0.977619
dtype: float64

In [29]:
accdata

      Meth.1    Meth.2
0   0.943968  0.943968
1   0.932857  0.932857
2   0.955079  0.955079
3   0.938254  0.938254
4   0.949365  0.949365
5   0.949524  0.949524
6   0.949524  0.949524
7   0.955238  0.955238
8   0.960794  0.960794
9   0.960794  0.960794
10  0.960952  0.960952
11  0.955238  0.955238
12  0.949524  0.949524
13  0.966349  0.966349
14  0.972063  0.972063
15  0.972063  0.972063
16  0.966508  0.966508
17  0.966508  0.966508
18  0.955397  0.955397
19  0.966508  0.966508
20  0.960952  0.960952
21  0.966508  0.966508
22  0.960952  0.960952
23  0.955238  0.955238
24  0.955238  0.955238
25  0.960794  0.960794
26  0.955238  0.955238
27  0.966349  0.966349
28  0.977619  0.977619
29  0.960794  0.960794
30  0.955238  0.955238
31  0.960794  0.960794
32  0.966349  0.966349
33  0.966349  0.966349
34  0.960794  0.960794
35  0.960794  0.960794
36  0.955238  0.955238
37  0.960794  0.960794
38  0.960794  0.960794
39  0.960794  0.960794
40  0.966349  0.966349
41  0.960794  0.960794
42  0.966349  0.966349
43  0.960635  0.960635
44  0.966349  0.966349
45  0.949524  0.949524
46  0.955079  0.955079
47  0.949524  0.949524
48  0.955079  0.955079
49  0.960635  0.960635